#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v18
# autospec commit: f35655a
#
Name     : pypi-setuptools
Version  : 74.1.2
Release  : 339
URL      : https://files.pythonhosted.org/packages/3e/2c/f0a538a2f91ce633a78daaeb34cbfb93a54bd2132a6de1f6cec028eee6ef/setuptools-74.1.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/3e/2c/f0a538a2f91ce633a78daaeb34cbfb93a54bd2132a6de1f6cec028eee6ef/setuptools-74.1.2.tar.gz
Summary  : Easily download, build, install, upgrade, and uninstall Python packages
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause MIT Python-2.0 ZPL-2.0
Requires: pypi-setuptools-bin = %{version}-%{release}
Requires: pypi-setuptools-license = %{version}-%{release}
Requires: pypi-setuptools-python = %{version}-%{release}
Requires: pypi-setuptools-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
.. |pypi-version| image:: https://img.shields.io/pypi/v/setuptools.svg
:target: https://pypi.org/project/setuptools

%package bin
Summary: bin components for the pypi-setuptools package.
Group: Binaries
Requires: pypi-setuptools-license = %{version}-%{release}

%description bin
bin components for the pypi-setuptools package.


%package license
Summary: license components for the pypi-setuptools package.
Group: Default

%description license
license components for the pypi-setuptools package.


%package python
Summary: python components for the pypi-setuptools package.
Group: Default
Requires: pypi-setuptools-python3 = %{version}-%{release}

%description python
python components for the pypi-setuptools package.


%package python3
Summary: python3 components for the pypi-setuptools package.
Group: Default
Requires: python3-core
Provides: pypi(setuptools)

%description python3
python3 components for the pypi-setuptools package.


%prep
%setup -q -n setuptools-74.1.2
cd %{_builddir}/setuptools-74.1.2
pushd ..
cp -a setuptools-74.1.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1725545164
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-setuptools
cp %{_builddir}/setuptools-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/0445ed0f69910eeaee036f09a39a13c6e1f37e12 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/backports.tarfile-1.2.0.dist-info/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/0445ed0f69910eeaee036f09a39a13c6e1f37e12 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/importlib_metadata-8.0.0.dist-info/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/importlib_resources-6.4.0.dist-info/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/inflect-7.3.1.dist-info/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/0445ed0f69910eeaee036f09a39a13c6e1f37e12 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/jaraco.context-5.3.0.dist-info/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/0445ed0f69910eeaee036f09a39a13c6e1f37e12 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/jaraco.functools-4.0.1.dist-info/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/0445ed0f69910eeaee036f09a39a13c6e1f37e12 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/jaraco.text-3.12.1.dist-info/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/0445ed0f69910eeaee036f09a39a13c6e1f37e12 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/more_itertools-10.3.0.dist-info/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/0d43a836dac65c0ea426ad49c881a1086600bf85 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/packaging-24.1.dist-info/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/pypi-setuptools/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/packaging-24.1.dist-info/LICENSE.BSD %{buildroot}/usr/share/package-licenses/pypi-setuptools/fdc0e4eabc45522b079deff7d03d70528d775dc0 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/platformdirs-4.2.2.dist-info/licenses/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/f511a8a63af8c6e36004b593478436bbc560ee0c || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/tomli-2.0.1.dist-info/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/9da6ca26337a886fb3e8d30efd4aeda623dc9ade || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/typeguard-4.3.0.dist-info/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/a51ccdcb7a9d8c2116d1dfc16f11b3c8a5830f67 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/typing_extensions-4.12.2.dist-info/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/c6e195f9aa30cc9b675d1612ca4fb7f74111bd35 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/wheel-0.43.0.dist-info/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-setuptools/5b39c45a91a556e5f1599604f1799e4027fa0e60 || :
cp %{_builddir}/setuptools-%{version}/setuptools/_vendor/zipp-3.19.2.dist-info/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools/0445ed0f69910eeaee036f09a39a13c6e1f37e12 || :
cp %{_builddir}/setuptools-%{version}/setuptools/config/_validate_pyproject/NOTICE %{buildroot}/usr/share/package-licenses/pypi-setuptools/3be8c90e01c5b03ec8a6816f1aa47e11894ec399 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
## Remove excluded files
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/setuptools/cli-32.exe
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/setuptools/cli-64.exe
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/setuptools/cli-arm64.exe
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/setuptools/cli.exe
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/setuptools/gui-32.exe
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/setuptools/gui-64.exe
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/setuptools/gui-arm64.exe
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/setuptools/gui.exe
## install_append content
mkdir -p %{buildroot}/usr/bin
echo "#!/bin/sh" > %{buildroot}/usr/bin/easy_install_is_deprecated
chmod 755 %{buildroot}/usr/bin/easy_install_is_deprecated
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/easy_install_is_deprecated

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-setuptools/0445ed0f69910eeaee036f09a39a13c6e1f37e12
/usr/share/package-licenses/pypi-setuptools/0d43a836dac65c0ea426ad49c881a1086600bf85
/usr/share/package-licenses/pypi-setuptools/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/pypi-setuptools/3be8c90e01c5b03ec8a6816f1aa47e11894ec399
/usr/share/package-licenses/pypi-setuptools/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/pypi-setuptools/5b39c45a91a556e5f1599604f1799e4027fa0e60
/usr/share/package-licenses/pypi-setuptools/9da6ca26337a886fb3e8d30efd4aeda623dc9ade
/usr/share/package-licenses/pypi-setuptools/a51ccdcb7a9d8c2116d1dfc16f11b3c8a5830f67
/usr/share/package-licenses/pypi-setuptools/c6e195f9aa30cc9b675d1612ca4fb7f74111bd35
/usr/share/package-licenses/pypi-setuptools/f511a8a63af8c6e36004b593478436bbc560ee0c
/usr/share/package-licenses/pypi-setuptools/fdc0e4eabc45522b079deff7d03d70528d775dc0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
